package tfgen

import (
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"

	"github.com/ivaninkv/tofu-resgen/internal/schema"
)

// header opens every generated file. The output is a starting point, not a
// frozen artefact: the parts a provider schema cannot describe (data source
// wiring and the like) are meant to be written by hand.
const header = "# Generated by tofu-resgen from the provider schema.\n\n"

// Options control generation of a single variables.tf.
type Options struct {
	// VarName is the module variable name, e.g. "compute".
	VarName string
	// ResourceName is the provider resource type, e.g. "yandex_compute_instance".
	ResourceName string
	// Description overrides the generated variable description.
	Description string
	// Doc emits schema descriptions as comments inside the object type.
	Doc bool
	// Defaults supplies values for optional attributes.
	Defaults *Defaults
}

// Generate renders variables.tf for one resource schema.
func Generate(res schema.Schema, opt Options) ([]byte, error) {
	if opt.VarName == "" {
		return nil, errors.New("variable name is required")
	}
	r := &Renderer{Defaults: opt.Defaults, Doc: opt.Doc}
	obj, err := r.objectType(nil, res.ConfigAttributes())
	if err != nil {
		return nil, err
	}
	desc := opt.Description
	if desc == "" {
		desc = fmt.Sprintf("Configuration for %s (map: instance name \u2192 object).", opt.ResourceName)
	}
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "variable %s {\n", strconv.Quote(opt.VarName))
	fmt.Fprintf(&b, "  description = %s\n", strconv.Quote(desc))
	fmt.Fprintf(&b, "  type        = map(%s)\n", obj)
	b.WriteString("  default     = {}\n}\n")
	return hclwrite.Format([]byte(b.String())), nil
}
